// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAdminTwoFactorDao is internal type for wrapping internal DAO implements.
type internalAdminTwoFactorDao = *internal.AdminTwoFactorDao

// adminTwoFactorDao is the data access object for table hg_admin_two_factor.
// You can define custom methods on it to extend its functionality as you wish.
type adminTwoFactorDao struct {
	internalAdminTwoFactorDao
}

var (
	// AdminTwoFactor is globally public accessible object for table hg_admin_two_factor operations.
	AdminTwoFactor = adminTwoFactorDao{
		internal.NewAdminTwoFactorDao(),
	}
)

// Fill with you ideas below.
