// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAdmin2faBackupCodeDao is internal type for wrapping internal DAO implements.
type internalAdmin2faBackupCodeDao = *internal.Admin2faBackupCodeDao

// admin2faBackupCodeDao is the data access object for table hg_admin_2fa_backup_code.
// You can define custom methods on it to extend its functionality as you wish.
type admin2faBackupCodeDao struct {
	internalAdmin2faBackupCodeDao
}

var (
	// Admin2faBackupCode is globally public accessible object for table hg_admin_2fa_backup_code operations.
	Admin2faBackupCode = admin2faBackupCodeDao{
		internal.NewAdmin2faBackupCodeDao(),
	}
)

// Fill with you ideas below.