// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAdmin2faConfigDao is internal type for wrapping internal DAO implements.
type internalAdmin2faConfigDao = *internal.Admin2faConfigDao

// admin2faConfigDao is the data access object for table hg_admin_2fa_config.
// You can define custom methods on it to extend its functionality as you wish.
type admin2faConfigDao struct {
	internalAdmin2faConfigDao
}

var (
	// Admin2faConfig is globally public accessible object for table hg_admin_2fa_config operations.
	Admin2faConfig = admin2faConfigDao{
		internal.NewAdmin2faConfigDao(),
	}
)

// Fill with you ideas below.