// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAdmin2faLogDao is internal type for wrapping internal DAO implements.
type internalAdmin2faLogDao = *internal.Admin2faLogDao

// admin2faLogDao is the data access object for table hg_admin_2fa_log.
// You can define custom methods on it to extend its functionality as you wish.
type admin2faLogDao struct {
	internalAdmin2faLogDao
}

var (
	// Admin2faLog is globally public accessible object for table hg_admin_2fa_log operations.
	Admin2faLog = admin2faLogDao{
		internal.NewAdmin2faLogDao(),
	}
)

// Fill with you ideas below.