// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAnixUserDao is internal type for wrapping internal DAO implements.
type internalAnixUserDao = *internal.AnixUserDao

// anixUserDao is the data access object for table anix_users.
// You can define custom methods on it to extend its functionality as you wish.
type anixUserDao struct {
	internalAnixUserDao
}

var (
	// AnixUser is globally public accessible object for table anix_users operations.
	AnixUser = anixUserDao{
		internal.NewAnixUserDao(),
	}
)