// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAnixChapterDao is internal type for wrapping internal DAO implements.
type internalAnixChapterDao = *internal.AnixChapterDao

// anixChapterDao is the data access object for table anix_chapters.
// You can define custom methods on it to extend its functionality as you wish.
type anixChapterDao struct {
	internalAnixChapterDao
}

var (
	// AnixChapter is globally public accessible object for table anix_chapters operations.
	AnixChapter = anixChapterDao{
		internal.NewAnixChapterDao(),
	}
)