// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalSysTwoFactorLogDao is internal type for wrapping internal DAO implements.
type internalSysTwoFactorLogDao = *internal.SysTwoFactorLogDao

// sysTwoFactorLogDao is the data access object for table sys_two_factor_log.
// You can define custom methods on it to extend its functionality as you wish.
type sysTwoFactorLogDao struct {
	internalSysTwoFactorLogDao
}

var (
	// SysTwoFactorLog is globally public accessible object for table sys_two_factor_log operations.
	SysTwoFactorLog = sysTwoFactorLogDao{
		internal.NewSysTwoFactorLogDao(),
	}
)

// Fill with you ideas below.