// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalUserTwoFactorDao is internal type for wrapping internal DAO implements.
type internalUserTwoFactorDao = *internal.UserTwoFactorDao

// userTwoFactorDao is the data access object for table hg_user_two_factor.
// You can define custom methods on it to extend its functionality as you wish.
type userTwoFactorDao struct {
	internalUserTwoFactorDao
}

var (
	// UserTwoFactor is globally public accessible object for table hg_user_two_factor operations.
	UserTwoFactor = userTwoFactorDao{
		internal.NewUserTwoFactorDao(),
	}
)

// Fill with you ideas below.
