// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalUserTwoFactorBackupCodesDao is internal type for wrapping internal DAO implements.
type internalUserTwoFactorBackupCodesDao = *internal.UserTwoFactorBackupCodesDao

// userTwoFactorBackupCodesDao is the data access object for table hg_user_two_factor_backup_codes.
// You can define custom methods on it to extend its functionality as you wish.
type userTwoFactorBackupCodesDao struct {
	internalUserTwoFactorBackupCodesDao
}

var (
	// UserTwoFactorBackupCodes is globally public accessible object for table hg_user_two_factor_backup_codes operations.
	UserTwoFactorBackupCodes = userTwoFactorBackupCodesDao{
		internal.NewUserTwoFactorBackupCodesDao(),
	}
)

// Fill with you ideas below.
